# Generated by Django 5.2 on 2025-04-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneverification_licenseverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
