# Generated by Django 5.2 on 2025-04-14 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_license_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('not_submitted', '미제출'), ('pending', '대기 중'), ('approved', '승인 완료'), ('rejected', '반려')], default='not_submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('not_submitted', '미제출'), ('pending', '대기 중'), ('approved', '승인 완료'), ('rejected', '반려')], default='not_submitted', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
