# Generated by Django 5.2 on 2025-04-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_is_verified_remove_user_license_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=1, max_length=20, verbose_name='이름'),
            preserve_default=False,
        ),
    ]
