# Generated by Django 5.2 on 2025-04-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseverification',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='licenseverification',
            name='status',
        ),
    ]
